# Generated by Django 3.1.7 on 2021-10-11 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_system', '0003_auto_20211011_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='managed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
