# Generated by Django 3.1.7 on 2021-10-12 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_system', '0005_auto_20211012_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='doctor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment_system.doctor'),
        ),
    ]
