# Generated by Django 3.1.7 on 2021-10-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_system', '0006_auto_20211012_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Doctor_Schedule',
        ),
    ]
